ci(installer): add CI to generate the installers
fix(installer): NSIS using deb install components

fix(installer): remove error on absolute path

fix(installer): moved lines, wrong else clause

feat(installer): add config for nsis

fix(installer): found a way to enforce which package are installed

cherry-pick: feat: fix crash because of m_layerInsert iterator

feat(installer): fix NSIS installer + add components to NSIS

feat(installer): add cache for GCC + fix path for installer testers

fix(installer): wrong working directory in action

fix(installer): cache miss + invalid installer names for download

fix(installer): run path

fix(installer): run scripts

fix(installer): windows did not wait for installer, deps for .deb

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,6 +4,7 @@ on: [push]
 
 jobs:
   build:
+    name: Build, test and Package
     strategy:
       fail-fast: false
       matrix:
@@ -31,6 +32,17 @@ jobs:
         uses: actions/checkout@v3
         with:
           submodules: recursive
+
+      - name: Pre-install GCC with cache
+        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc' }}
+        uses: awalsh128/cache-apt-pkgs-action@latest
+        with:
+          packages: cpp-13 g++-13 gcc-13 gcc-13-base libgcc-13-dev libhwasan0 \
+            libstdc++-13-dev libasan8 libatomic1 libcc1-0 libgcc-13-dev \
+            libgcc-s1 libgomp1 libhwasan0 libitm1 liblsan0 libquadmath0 \
+            libstdc++-13-dev libstdc++6 libtsan2 libubsan1
+          version: 1.0
+          execute_install_scripts: true
 
       - name: Set up GCC
         if: ${{ matrix.compiler == 'gcc' }}
@@ -101,11 +113,100 @@ jobs:
         shell: bash
         run: |
           mkdir -p output
-          cmake --install build --prefix ./output --config Debug -v
+          cmake --install build --component Unspecified --prefix ./output --config Debug -v
 
       - name: Upload package
         uses: actions/upload-artifact@v4
         with:
-          name: nexo-editor-${{ matrix.compiler }}${{ matrix.version }}-${{ matrix.os }}
+          name: nexo-engine-${{ matrix.compiler }}${{ matrix.version }}-${{ matrix.os }}
           path: |
             ./output/*
+
+      - name: Generate NSIS installer
+        if: ${{ matrix.os == 'windows-latest' }}
+        shell: bash
+        run: |
+          choco install -y nsis
+          cd build
+          cpack -G NSIS --verbose
+
+      - name: Generate DEB installer
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        shell: bash
+        run: |
+          cd build
+          cpack -G DEB --verbose
+
+      - name: Upload installer packages
+        uses: actions/upload-artifact@v4
+        with:
+          name: nexo-engine-installer-${{ matrix.compiler }}${{ matrix.version }}-${{ matrix.os }}
+          path: |
+            build/NEXO-Engine-*-win64.exe
+            build/*.deb
+
+  test-nsis-installer:
+    name: Test NSIS installer
+    runs-on: windows-latest
+    needs: build
+    steps:
+      - name: Download NSIS installer
+        id: download
+        uses: actions/download-artifact@v4
+        with:
+          pattern: 'nexo-engine-installer-msvc14-windows-latest'
+
+      - name: Run NSIS installer
+        shell: pwsh
+        run: |
+          # Find the first .exe file in the downloaded directory
+          $exePath = Get-ChildItem -Path "${{steps.download.outputs.download-path}}\nexo-engine-installer-msvc14-windows-latest" -Filter "*.exe" | Select-Object -First 1 -ExpandProperty FullName
+      
+          if (-not $exePath) {
+            Write-Error "No .exe file found in the directory."
+            exit 1
+          }
+          
+          # Run the installer with /S for silent mode and /D to specify the installation directory
+          Start-Process -FilePath "$exePath" -wait -ArgumentList "/S /D=C:\Program Files\NexoEngine"
+          
+
+
+      - name: Run NEXO
+        shell: pwsh
+        run: |
+          $exePath = "C:\Program Files\NexoEngine\bin\nexoEditor.exe"
+          
+          # Start the process and wait for up to 10 seconds
+          $process = Start-Process -FilePath $exePath -NoNewWindow -PassThru
+          if ($process.WaitForExit(10000)) {
+            # Exit with the process exit code
+            exit $process.ExitCode
+          } else {
+            # If the process doesn't exit within 10 seconds, terminate it
+            Stop-Process -Id $process.Id -Force
+          }
+
+          # Exit with success
+          exit 0
+
+  test-deb-installer:
+    name: Test DEB installer
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download DEB installer
+        id: download
+        uses: actions/download-artifact@v4
+        with:
+          pattern: 'nexo-engine-installer-gcc13-ubuntu-latest'
+
+      - name: Install DEB package
+        shell: bash
+        run: |
+          sudo apt -f install ${{steps.download.outputs.download-path}}/nexo-engine-installer-gcc13-ubuntu-latest/*.deb
+
+      - name: Run NEXO
+        shell: bash
+        run: |
+          timeout --preserve-status 10s nexoEditor
